# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/axis/Desktop/Code/CPUSimer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/axis/Desktop/Code/CPUSimer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/axis/Desktop/Code/CPUSimer/CMakeFiles /Users/axis/Desktop/Code/CPUSimer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/axis/Desktop/Code/CPUSimer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpusimer

# Build rule for target.
cpusimer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpusimer
.PHONY : cpusimer

# fast build rule for target.
cpusimer/fast:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/build
.PHONY : cpusimer/fast

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/Main.cpp.s
.PHONY : Main.cpp.s

Stub.o: Stub.cpp.o

.PHONY : Stub.o

# target to build an object file
Stub.cpp.o:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/Stub.cpp.o
.PHONY : Stub.cpp.o

Stub.i: Stub.cpp.i

.PHONY : Stub.i

# target to preprocess a source file
Stub.cpp.i:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/Stub.cpp.i
.PHONY : Stub.cpp.i

Stub.s: Stub.cpp.s

.PHONY : Stub.s

# target to generate assembly for a file
Stub.cpp.s:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/Stub.cpp.s
.PHONY : Stub.cpp.s

UnicornWrapper.o: UnicornWrapper.cpp.o

.PHONY : UnicornWrapper.o

# target to build an object file
UnicornWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/UnicornWrapper.cpp.o
.PHONY : UnicornWrapper.cpp.o

UnicornWrapper.i: UnicornWrapper.cpp.i

.PHONY : UnicornWrapper.i

# target to preprocess a source file
UnicornWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/UnicornWrapper.cpp.i
.PHONY : UnicornWrapper.cpp.i

UnicornWrapper.s: UnicornWrapper.cpp.s

.PHONY : UnicornWrapper.s

# target to generate assembly for a file
UnicornWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/cpusimer.dir/build.make CMakeFiles/cpusimer.dir/UnicornWrapper.cpp.s
.PHONY : UnicornWrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cpusimer"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Stub.o"
	@echo "... Stub.i"
	@echo "... Stub.s"
	@echo "... UnicornWrapper.o"
	@echo "... UnicornWrapper.i"
	@echo "... UnicornWrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

